job_path: jobs/noncwcot_file_formatter
system_files:
  seller_matrix: <%= ENV['SELLER_MATRIX'] %>
  seller_datatape: <%= ENV['SELLER_DATATAPE'] %>
  asset_load: <%= ENV['ASSET_LOAD'] %>
required_fields:
  matrix:
    - Seller Code
    - Servicer
    - Servicer Account ID for Asset
    - Tracking ID Prefix for all other objects
    - REO Alt D Record Type ID
    - Auction Record Type ID
logger:
  filename: ../logs/logfile.log
  frequency: daily