job_path: jobs/equator_messenger

equator:
  bac:
    url: <%=ENV['EQ_URL']%>
    username: <%=ENV['EQ_BAC_USER']%>
    password: <%=ENV['EQ_BAC_PASS']%>

logger:
  filename: ../logs/logfile.log
  frequency: daily
