job_path: jobs/sftp_file_copy

logger:
  filename: ../logs/logfile.log
  frequency: daily

sftp_path: TEST/Outbound
local_path: home/salesfuser/Informatica/CMT/pacific-union/Stage
base_filename: CWCOT_ADC_NewReferral
