# SFDC connection settings
salesforce:
  # The external instance of SFDC
  external:

    # Production credentials 
    production:
      host: login.salesforce.com
      instance_url: <%= ENV['SF_PROD_URL'] %>
      username: <%= ENV['SF_PROD_USER'] %>
      password: <%= ENV['SF_PROD_PWD'] %>
      security_token: <%= ENV['SF_PROD_TOKEN'] %>
      client_id: <%= ENV['SF_PROD_CID'] %>
      client_secret: <%= ENV['SF_PROD_CLS'] %>

    # Development (sandbox) credentials
    development:
      host: test.salesforce.com
      instance_url: <%= ENV['SF_DEV_URL'] %>
      username: <%= ENV['SF_DEV_USER'] %>
      password: <%= ENV['SF_DEV_PWD'] %>
      security_token: <%= ENV['SF_DEV_TOKEN'] %>
      client_id: <%= ENV['SF_DEV_CID'] %>
      client_secret: <%= ENV['SF_DEV_CLS'] %>

  internal:

    # Production credentials 
    production:
      host: login.salesforce.com
      instance_url: <%= ENV['SFINT_PROD_URL'] %>
      username: <%= ENV['SFINT_PROD_USER'] %>
      password: <%= ENV['SFINT_PROD_PWD'] %>
      security_token: <%= ENV['SFINT_PROD_TOKEN'] %>
      client_id: <%= ENV['SFINT_PROD_CID'] %>
      client_secret: <%= ENV['SFINT_PROD_CLS'] %>

smtp:
  host: <%= ENV['ADC_SMTP_HOST'] %>
  port: <%= ENV['ADC_SMTP_PORT'] %>
  domain: <%= ENV['ADC_SMTP_DOMAIN'] %>
  username: <%= ENV['ADC_SMTP_USER'] %>
  password: <%= ENV['ADC_SMTP_PASS'] %>
  from_addr: <%= ENV['ADC_SMTP_FROM'] %>
  to_addr: <%= ENV['ADC_SMTP_TO'] %>
  cc_list: <%= ENV['ADC_SMTP_CC'] %>

sftp:
  closing:
    host: <%= ENV['CLS_SFTP_HOST'] %>
    port: <%= ENV['CLS_SFTP_PORT'] %>
    username: <%= ENV['CLS_SFTP_USER'] %>
    password: <%= ENV['CLS_SFTP_PWD'] %>

  cwcot:
    host: <%= ENV['CWCOT_SFTP_HOST'] %>
    port: <%= ENV['CWCOT_SFTP_PORT'] %>
    username: <%= ENV['CWCOT_SFTP_USER'] %>
    password: <%= ENV['CWCOT_SFTP_PWD'] %>

logger:
  filename: ../logs/logfile.log
  frequency: daily