job_path: jobs/offer_mcds_true_up

logger:
  filename: ../logs/logfile.log
  frequency: daily

uaa:
  endpoint: <%= ENV['UAA_ENDPOINT'] %>
  grant_type: <%= ENV['UAA_GRANT_TYPE'] %>
  client_id: <%= ENV['UAA_CID'] %>
  client_secret: <%= ENV['UAA_CSC'] %>

contract:
  offers_endpoint: <%= ENV['CONTRACT_OFFERS_ENDPOINT'] %>
  contracts_endpoint: <%= ENV['CONTRACT_CONTRACTS_ENDPOINT'] %>